In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

from sklearn import datasets
from sklearn.model_selection import train_test_split

# 平均一天喝幾杯含糖飲料易得糖尿病

In [3]:
data = pd.read_csv('LogR_data.csv')

In [4]:
data

Name  Amount  Result
0      Jack       0       0
1       Amy       1       1
2      John       3       1
3      Anna       2       1
4      Nick       1       0
5   Jocelyn       1       0
6       Bob       0       0
7     Candy       0       1
8      Lily       1       0
9     Grace       0       0
10    Jason       2       1
11    Bryan       3       1
12     Ryan       3       1
13     Tina       2       0
14     Jane       2       1
15     Alex       0       0
16     Yoyo       2       1
17    Alice       3       1
18    Frank       2       0
19     Boss       3       0

In [6]:
#平均一天喝飲料量
X = data['Amount'].values
#是否得糖尿病
y = data['Result'].values

In [7]:
X.shape

(20,)

In [8]:
X = X.reshape(-1,1)

# 建模

In [9]:
model = linear_model.LogisticRegression()
model.fit(X,y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [12]:
model.predict([[0],[1],[2],[3]])

array([0, 0, 1, 1], dtype=int64)

In [15]:
X

array([[0],
       [1],
       [3],
       [2],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [2],
       [3],
       [3],
       [2],
       [2],
       [0],
       [2],
       [3],
       [2],
       [3]], dtype=int64)

In [14]:
#預測輸入資料分類機率，第一筆資料輸入分為0的機率是0.78616997，分為1的機率是0.21383003
model.predict_proba(X)

array([[0.78616997, 0.21383003],
       [0.61473154, 0.38526846],
       [0.23107565, 0.76892435],
       [0.40914498, 0.59085502],
       [0.61473154, 0.38526846],
       [0.61473154, 0.38526846],
       [0.78616997, 0.21383003],
       [0.78616997, 0.21383003],
       [0.61473154, 0.38526846],
       [0.78616997, 0.21383003],
       [0.40914498, 0.59085502],
       [0.23107565, 0.76892435],
       [0.23107565, 0.76892435],
       [0.40914498, 0.59085502],
       [0.40914498, 0.59085502],
       [0.78616997, 0.21383003],
       [0.40914498, 0.59085502],
       [0.23107565, 0.76892435],
       [0.40914498, 0.59085502],
       [0.23107565, 0.76892435]])

In [16]:
model.score(X,y)

0.75

# 多元分類
拆成兩兩分類之後再綜合起來就可完成多元分類，以鳶尾花為例，先將1與2,3分開，再將2與1,3獨立，在獨立出3，最後在合併。

In [19]:
iris = datasets.load_iris()

In [20]:
X = iris.data
y = iris.target

In [22]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

In [23]:
model = linear_model.LogisticRegression()

In [24]:
model.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [25]:
model.predict(X_test)

array([0, 2, 2, 1, 1, 0, 0, 1, 1, 0, 0, 2, 1, 0, 0, 0, 0, 1, 2, 0, 2, 1,
       2, 1, 1, 1, 0, 1, 2, 1, 0, 2, 0, 0, 1, 0, 2, 1, 0, 2, 0, 0, 0, 1,
       1])

In [26]:
model.predict_proba(X_test)

array([[9.64822748e-01, 3.51770907e-02, 1.61276755e-07],
       [1.22613175e-05, 1.58981127e-02, 9.84089626e-01],
       [1.50426758e-05, 2.94569390e-02, 9.70528018e-01],
       [2.33351549e-02, 8.92807598e-01, 8.38572469e-02],
       [3.78742699e-03, 7.65456471e-01, 2.30756102e-01],
       [9.46806948e-01, 5.31921323e-02, 9.19420133e-07],
       [9.78464497e-01, 2.15354561e-02, 4.66677810e-08],
       [1.72320003e-02, 8.16059812e-01, 1.66708187e-01],
       [2.52646966e-02, 9.25368750e-01, 4.93665539e-02],
       [9.56595588e-01, 4.34042630e-02, 1.48982380e-07],
       [9.66190296e-01, 3.38095841e-02, 1.19495485e-07],
       [7.07081557e-06, 1.75807091e-02, 9.82412220e-01],
       [3.41256800e-03, 5.10716394e-01, 4.85871038e-01],
       [9.67566602e-01, 3.24333096e-02, 8.80717342e-08],
       [9.69715897e-01, 3.02840392e-02, 6.35066748e-08],
       [9.35419984e-01, 6.45797392e-02, 2.77298751e-07],
       [9.80667314e-01, 1.93326124e-02, 7.35497376e-08],
       [1.15560957e-03, 5.54708

In [28]:
model.score(X_train,y_train)

0.9809523809523809

In [29]:
model.score(X_test,y_test)

0.8888888888888888